### PR TITLE
158 fixing upload image issue

### LINKED ISSUE #158: Possibly fixing Issue for Image Upload
Attempting to pass in image with ampersand(&) in the name causes issues. Collyn mentioned it might be because the character may be a reserved keyword for packages but I can't confirm yet.

### PR DESCRIPTION
**Pull request by dmols**
The creator is now unable to upload images with names that do not contain any symbols that are not alphanumeric. Did this check in both the frontend and the backend to disallow the invalid entry of files into our system. I want only alphanumeric filenames since some symbols could be harmful and bring up security issues.

### CODE REVIEW

**Comment by dmols** [comment]
This also means the filename cannot have spaces, but that is common practice anyways. It may be a little annoying on the user not to use spaces for their files, but preventing any non-alphanumeric symbols in the filename may leave our code less vulnerable to attacks.

File: server/routes/fileMulter.js [hunk 1]
```diff
@@ -21,7 +21,31 @@ const upload = multer({ storage: fileStorageEngine })
...
+  let validImageTypes = ["png", "PNG", "jpeg", "jpg"]
+
+  // Checking to see if the extension is one of the valid types
+  const imageTypePath = req.query.imageName.split('.')
+  const imageType = imageTypePath[imageTypePath.length - 1]
+  const validInput = validImageTypes.includes(imageType);
+
+  // If it isn't, return and allow user to input valid image
+  if (!validInput) {
+    console.log('Invalid file type. Please upload an image with the extension .jpg or .png')
```
Comment (mbrancato31) [inline server/routes/fileMulter.js]: is this debugging? also if not, you are only saying 2 of the 4 file types but since this is the server, this should not print anything really

File: frontend/toolkit-webapp/src/pages/Course.js [hunk 2]
```diff
@@ -135,6 +134,17 @@ const Course = (props) => {
...
     }
 
+    // Check that the input given is alphanumeric to avoid the possibility of commands being 
+    // passed in to the backend
+    var val = imageTypePath[imageTypePath.length - 2];
+    var RegEx = /[^0-9a-z]/i;
+    var isValid = !(RegEx.test(val));
+
+    if (isValid === false) {
+      alert('Invalid file type. Please upload an image for which name is aplhanumeric.')
```
Comment (collyntheshots) [inline frontend/toolkit-webapp/src/pages/Course.js]: "aplhanumeric" should be "alphanumeric"

Comment (collyntheshots) [inline frontend/toolkit-webapp/src/pages/Course.js]: "aplhanumeric" should be "alphanumeric"

**Review by collyntheshots — CHANGES_REQUESTED** [review]
Besides what has been commented everything looks good

File: server/routes/fileMulter.js (hunk 1 above)
Comment (dmols) [reply server/routes/fileMulter.js]: It's disallowing any wrong file type. I'll send a message back instead, good idea.

**Review by collyntheshots — APPROVED** [review]
